'use strict';
// Trimmed from the full CoreSense Studio build: this is only the "import an existing ROS
// source workspace" flow (extracting node contracts and launch structure from real source,
// without executing it, and adopting the result as this project's model). Everything else that
// used to live in this file -- execution-unit/container configuration, the source-repository
// catalogue browser (superseded by the React RepositoryWorkspace in repositories.jsx), reviews
// and delivery manifests -- belonged to the deployment/release tool, which this app does not
// include.
async function showSourceImport(){if(!await flush())return;const r=await api(`/projects/${A.env.projectId}/source/inspect`);A.sourceInventory=r;modal('Review existing ROS source',`<p>Extract node contracts and launch structure without executing your launch file. Existing source files are preserved.</p><label class="field">Source directory (relative to this project)<input id="source-root" value="${esc(r.sourcePath||'src')}"></label><label class="field">Launch file (relative to this project)<input id="source-launch" list="source-launches" value="${esc(r.launchFiles?.[0]?.path||r.launchFiles?.[0]||'')}"><datalist id="source-launches">${(r.launchFiles||[]).map(f=>`<option value="${esc(f.path||f)}">`).join('')}</datalist></label><label class="field">System name<input id="source-system" value="${esc(name())}"></label><button data-engineering="source-preview" class="primary">Extract and compare</button>`)}
async function showSourcePreview(){const root=$('#source-root').value.trim(),body={launchPath:$('#source-launch').value,systemName:$('#source-system').value};if(root)body.sourcePath=root;A.sourcePlan=await api(`/projects/${A.env.projectId}/source/preview`,{method:'POST',body});const p=A.sourcePlan;modal('Source-derived model proposal',`<p>${p.project.nodes.length} node contracts. Review unresolved facts before adoption. Existing brief and criteria will be retained.</p><pre>${esc(JSON.stringify({diagnostics:p.diagnostics,flags:p.flags,coverage:p.coverage},null,2))}</pre><h3>Connection candidates</h3><p class="mini">Matching source topics are proposals; choose the connections you intend to model.</p>${(p.candidateConnections||[]).map(c=>`<label class="row"><input type="checkbox" data-source-connection="${esc(c.id)}">${esc(c.label||JSON.stringify(c))}</label>`).join('')||'<p>No inferred connection candidates.</p>'}<details><summary>Changes from current model</summary><pre>${esc(JSON.stringify(p.changes,null,2))}</pre></details>${p.files.map(f=>`<details><summary>${esc(f.path)}</summary><pre>${esc(f.content)}</pre></details>`).join('')}<button data-engineering="source-apply" class="primary">Adopt reviewed model draft</button>`)}
function roleDescription(role){return {Afferent:'Sense and acquire information from the world.',Core:'Reason, plan and coordinate behavior.',Efferent:'Act on the world through commands and hardware.',Meta:'Monitor, explain and adapt the system itself.',Supporting:'Shared infrastructure and supporting services.'}[role]||'Assign a responsibility to connect this ROS module to the CoreSense architecture.'}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;(async()=>{
  const action=b.dataset.engineering;if(!action)return;
  if(action==='open-source-workspace'){modal('Open an existing ROS workspace',`<label class="field">Workspace path<input id="existing-source-path" placeholder="/media/HDD/git/my_robot"></label><p>The source stays in place. Studio adds project.json and recovery metadata if this workspace is not already a Studio project.</p><button data-engineering="adopt-source-workspace" class="primary">Open source workspace</button>`)}
  if(action==='adopt-source-workspace'){if(!await flush())return;const r=await api('/projects/source',{method:'POST',body:{path:$('#existing-source-path').value}});setEnvelope(r);sessionStorage.setItem('studioActiveProject',r.projectId);closeModal();A.session.view='Architecture';A.session.tab='system';sessionEdit();render();await showSourceImport()}
  if(action==='source-import')await showSourceImport();
  if(action==='source-preview')await showSourcePreview();
  if(action==='source-apply'){const acceptedConnections=$$('[data-source-connection]:checked').map(e=>e.dataset.sourceConnection);const r=await api(`/projects/${A.env.projectId}/source/import`,{method:'POST',body:{planId:A.sourcePlan.planId,expectedRevision:A.env.revision,acceptedConnections}});setEnvelope(r,A.session);closeModal();render();banner('Reviewed source model saved as a draft. Preview model artifacts to accept its generated files.')}
})().catch(e=>{b.disabled=false;if($('#dialog').open){const error=document.createElement('p');error.className='error';error.textContent=e.message;$('#dialog-body').append(error)}else banner(e.message)})});
