'use strict';
let studioTools=[];
async function loadTools(){const r=await api('/plugins');studioTools=r.tools;if(A.env)renderShortcuts()}
function availableTools(){return studioTools.filter(t=>!(A.session.disabledTools||[]).includes(t.id))}
function renderShortcuts(){const target=$('.nav-end');if(!target)return;const ids=A.session.shortcuts||['coding-cli'];target.innerHTML=ids.map(id=>availableTools().find(t=>t.id===id)).filter(Boolean).map(t=>`<button class="shortcut-icon" data-run-tool="${esc(t.id)}" aria-label="${esc(t.name)}" title="${esc(t.name)}">${esc(t.icon||t.name[0])}</button>`).join('')+'<button data-toolbox="manage" title="Customize shortcuts and plugins" aria-label="Customize shortcuts and plugins">⋯</button>'}
function contextualTools(){modal('Tools for '+A.session.view,`<p class="mini">Installed tools appear where they apply. The same simulation workspace and coding session are reused.</p><div class="tool-cards">${availableTools().filter(t=>(t.stages||[]).includes(A.session.view)).map(t=>`<button data-run-tool="${esc(t.id)}"><b>${esc(t.icon||'◇')} ${esc(t.name)}</b><span class="mini">${esc((t.outputs||[]).join(' · '))}</span></button>`).join('')}</div><button data-toolbox="manage">Manage tools and shortcuts</button>`)}
function manageTools(){modal('Tools & shortcuts',`<p>Choose enabled tools and the shortcut icons shown beside the lifecycle. These preferences are saved with your workspace session.</p>${studioTools.map(t=>`<section class="tool-setting"><label><input type="checkbox" data-tool-enabled="${esc(t.id)}" ${availableTools().some(x=>x.id===t.id)?'checked':''}> ${esc(t.name)}</label><label class="mini"><input type="checkbox" data-tool-shortcut="${esc(t.id)}" ${(A.session.shortcuts||['coding-cli']).includes(t.id)?'checked':''}> Shortcut</label><p class="mini">${esc((t.stages||[]).join(' → '))}${t.skill?' · Domain skill: '+esc(t.skill):''}</p></section>`).join('')}<p class="mini">Local extensions live in web/studio/plugins/&lt;id&gt;/plugin.json. Only install code you trust; these are local workspace tools.</p><button data-toolbox="save" class="primary">Save tool preferences</button>`)}
async function runStudioTool(id){const tool=availableTools().find(t=>t.id===id);if(!tool)return;closeModal();if(tool.action==='repositories'){await repositoriesPanel();return}if(tool.action==='source-import'){await showSourceImport();return}if(tool.action){await action(tool.action);return}if(tool.entry){modal(tool.name,`<iframe class="physics-frame" title="${esc(tool.name)}" src="${esc(tool.entry)}"></iframe>`)} }
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;(async()=>{if(b.dataset.runTool)await runStudioTool(b.dataset.runTool);if(b.dataset.toolbox==='manage')manageTools();if(b.dataset.toolbox==='save'){A.session.disabledTools=$$('[data-tool-enabled]').filter(e=>!e.checked).map(e=>e.dataset.toolEnabled);A.session.shortcuts=$$('[data-tool-shortcut]:checked').map(e=>e.dataset.toolShortcut);sessionEdit();closeModal();renderShortcuts()}})().catch(e=>banner(e.message))});
loadTools().catch(e=>console.warn('Tool manifest could not be read:',e.message));
