'use strict';
let tutorialBusy=false;
function tutorialProof(key,value=true){if(!A.session.tutorial)return;A.session.tutorialProof=A.session.tutorialProof||{};A.session.tutorialProof[key]=value;sessionEdit()}
function renderTutorialPanel(){$$('.tutorial-target').forEach(e=>e.classList.remove('tutorial-target'));const t=currentTutorial(),el=$('#tutorial');if(!t){el.classList.add('hidden');return}const idx=A.session.tutorial.step,step=t.steps[idx];el.classList.remove('hidden');if(!step){const results=A.session.tutorial.results||{},skipped=Object.values(results).filter(v=>v.skipped).length;el.innerHTML=`<h2>Walkthrough finished</h2><p>${Object.keys(results).length-skipped} steps verified from saved artifacts or observed actions. ${skipped} steps explicitly skipped.</p><p class="mini">The walkthrough records what you did. Read the check outcomes before deciding whether the system meets its requirements.</p>${B('Close tutorial','tutorial-close')}`;return}el.innerHTML=`<div class="row between"><span class="mini">${esc(t.title)} · ${idx+1}/${t.steps.length}</span>${B('×','tutorial-close','','aria-label="Close tutorial"')}</div><h3>${esc(step.title)}</h3><p>${esc(step.body)}</p><p id="tutorial-proof-status" class="mini" role="status">Next verifies this step against saved work or actual tool output.</p><div class="row">${B('Show control','tutorial-focus')}${B('Back','tutorial-back','',idx?'':'disabled')}${B('Next','tutorial-next','primary')}<button data-tutorial-skip>Skip with reason</button></div>`;document.getElementById(step.target)?.classList.add('tutorial-target')}
// Only the checks the shipped walkthrough still uses live here. The Deploy/telemetry/physics
// checks were removed with the features they verified -- keeping them would have meant shipping
// code that calls /deployment/status and /telemetry/status, routes this server no longer has.
async function tutorialCheck(key){if(!await flush())return {ok:false,message:'Resolve the pending save before continuing.'};const proof=A.session.tutorialProof||{},env=A.env,project=A.project;let records=[];if(key==='model-check-recorded'){const index=await api(`/projects/${env.projectId}/evidence`);records=await Promise.all(index.records.map(async r=>(await api(`/projects/${env.projectId}/evidence/${r.id}`)).evidence))}let ok=false;switch(key){
case 'project-ready':ok=Boolean(env.projectId&&env.root);break;
case 'brief-saved':ok=Boolean(project.studio.brief.purpose?.trim()&&project.studio.brief.acceptance?.trim()&&!A.dirty);break;
case 'starter-nodes':ok=project.nodes.length>=2;break;
case 'connection-present':ok=project.connections.some(c=>project.nodes.some(n=>n.id===c.from.n&&n.ifaces.some(f=>f.id===c.from.i))&&project.nodes.some(n=>n.id===c.to.n&&n.ifaces.some(f=>f.id===c.to.i)));break;
case 'model-check-recorded':ok=records.some(r=>r.kind==='check'&&(r.checks||[]).some(c=>c.tool==='ros_studio.validate_project'));break;
case 'project-reopened':ok=Boolean(proof.projectReopened);break;
default:return {ok:false,message:'This tutorial check is unavailable: '+key};}
return {ok:Boolean(ok),message:ok?'Verified against actual saved work.':'Complete the described action, then choose Next. You can explicitly skip with a reason if a prerequisite is unavailable.'}}
async function advanceTutorial(direction){
 if(tutorialBusy)return;const t=currentTutorial(),session=A.session.tutorial,projectId=A.env?.projectId;if(!t||!session)return;
 tutorialBusy=true;const buttons=$$('#tutorial [data-action="tutorial-next"],#tutorial [data-action="tutorial-back"]');buttons.forEach(b=>b.disabled=true);
 try{if(direction>0){const step=t.steps[session.step];if(!step)return;const status=$('#tutorial-proof-status');if(status)status.textContent='Checking saved work…';const proof=await tutorialCheck(step.check);if(A.env?.projectId!==projectId||A.session.tutorial!==session)return;if(!proof.ok){if($('#tutorial-proof-status'))$('#tutorial-proof-status').textContent=proof.message;return}session.results=session.results||{};session.results[step.id]={verifiedAt:new Date().toISOString(),check:step.check}}
 session.step=Math.max(0,session.step+direction);sessionEdit();const next=t.steps[session.step];if(next?.view)await changeView(next.view,next.tab);else renderTutorial();
 }finally{tutorialBusy=false;const next=$('#tutorial [data-action="tutorial-next"]'),back=$('#tutorial [data-action="tutorial-back"]');if(next)next.disabled=false;if(back)back.disabled=!A.session.tutorial?.step}
}
async function focusTutorialControl(){const step=currentTutorial()?.steps[A.session.tutorial.step];if(!step)return;if(step.view)await changeView(step.view,step.tab);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));const el=step.selector?document.querySelector(step.selector):step.controlText?[...document.querySelectorAll('#main button,header button')].find(b=>b.textContent.trim()===step.controlText):document.getElementById(step.target);if(el){el.classList.add('tutorial-target');el.scrollIntoView({block:'center',behavior:'smooth'});el.focus?.()}else banner('The control becomes available after its prerequisite in this step.');}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(tutorialBusy)return;if(b.hasAttribute('data-tutorial-skip'))modal('Skip this tutorial step',`<p>A skipped step is recorded separately from a verified action.</p><label class="field">Reason<textarea id="tutorial-skip-reason"></textarea></label><button data-tutorial-confirm-skip>Record skip</button>`);if(b.hasAttribute('data-tutorial-confirm-skip')){const reason=$('#tutorial-skip-reason').value.trim();if(!reason)return;const t=currentTutorial(),s=A.session.tutorial,step=t.steps[s.step];s.results=s.results||{};s.results[step.id]={skipped:true,reason,time:new Date().toISOString()};s.step++;sessionEdit();closeModal();const next=t.steps[s.step];if(next?.view)changeView(next.view,next.tab).catch(mutationFailure);else renderTutorial()}});
