import React,{useEffect,useState,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {flushSync} from 'react-dom';
import {renderToStaticMarkup} from 'react-dom/server';
import {Group,Panel,Separator,usePanelRef,useGroupRef} from 'react-resizable-panels';
import {Box,Compass,Code2,ShieldCheck,Container,PanelLeftClose,PanelRightClose,PanelLeftOpen,PanelRightOpen,Sparkles,Search,BookOpen,History,Settings2,ChevronLeft,ChevronRight,ArrowRight,Play,X,FolderGit2,FileCode,CheckCheck,Download,GitCompare,RefreshCw,Layers} from 'lucide-react';
import {useStudio,changed,mount,release,roots,IconButton,Field,go,undo,redo} from './state';
import {ArchitectureGraph,Catalogue,ComponentInspector,connectInterfaces,connectionProblem,instantiate} from './architecture';
import {Intent,IntentGuide} from './intent';
import {TypesWorkspace} from './types';
import {RepositoryWorkspace,loadLocalCatalogue} from './repositories';
import {ChecksView,ChecksExplorer,HumanData,humanizeLegacyDOM} from './viewers';
import '@xyflow/react/dist/style.css';
import './studio.css';
const old={render,context,edit,sessionEdit,setEnvelope,modal,develop,validateView,evidenceView,showJob,refreshArtifacts,renderShortcuts,landing,renderTutorial};
const DEFAULT_LAYOUT={catalogue:21,work:56,details:23},MOBILE_LAYOUT={catalogue:0,work:100,details:0};function mobileLayout(){return {catalogue:A.session.mobilePane==='left'?100:0,work:A.session.mobilePane?0:100,details:A.session.mobilePane==='right'?100:0}};const panelRefs={};let lastProject=null,legacyMode=false;
function Frame(){useStudio();const left=usePanelRef(),right=usePanelRef(),group=useGroupRef(),restored=useRef('');panelRefs.left=left;panelRefs.right=right;panelRefs.group=group;const stage=A.session.view||'Architecture',narrow=innerWidth<=900;useEffect(()=>{if(!A.env)return;if(narrow){requestAnimationFrame(()=>group.current?.setLayout(mobileLayout()));return}const layout=A.session.splitLayouts?.[stage];const p=panelState();if(p.left||stage==='Deploy')left.current?.collapse();else if(left.current?.isCollapsed())left.current.expand();if(p.right)right.current?.collapse();else if(right.current?.isCollapsed())right.current.expand();if(layout)requestAnimationFrame(()=>group.current?.setLayout(layout))},[stage,A.env?.projectId,A.session.panels?.[stage]?.left,A.session.panels?.[stage]?.right,JSON.stringify(A.session.splitLayouts?.[stage]),narrow,A.session.mobilePane]);return <Group id="engineering-panels" className="engineering-panels" groupRef={group} orientation="horizontal" defaultLayout={narrow?mobileLayout():A.session.splitLayouts?.[stage]||DEFAULT_LAYOUT} onLayoutChanged={(layout,meta)=>{if(!A.env)return;if(narrow){const target=mobileLayout(),key=A.env.projectId+':mobile:'+A.session.mobilePane;if(restored.current!==key&&Object.keys(layout).length===3){restored.current=key;requestAnimationFrame(()=>group.current?.setLayout(target))}return}if(!meta.isUserInteraction){const target=A.session.splitLayouts?.[A.session.view],key=A.env.projectId+':'+A.session.view+':'+JSON.stringify(target);if(target&&restored.current!==key&&Object.keys(layout).length===3){restored.current=key;requestAnimationFrame(()=>group.current?.setLayout(target))}return}A.session.splitLayouts=A.session.splitLayouts||{};A.session.splitLayouts[stage]=layout;const p=panelState();p.left=layout.catalogue===0;p.right=layout.details===0;old.sessionEdit();context()}}><Panel id="catalogue" defaultSize="21%" minSize={narrow?0:"180px"} maxSize={narrow?"100%":"42%"} collapsible panelRef={left}><aside id="explorer" inert={narrow&&A.session.mobilePane!=='left'} aria-label="Workspace explorer"/></Panel><Separator className="panel-separator" aria-label="Resize explorer"/><Panel id="work" minSize={narrow?0:"280px"} collapsible={narrow}><main id="main" inert={narrow&&!!A.session.mobilePane}/></Panel><Separator className="panel-separator" aria-label="Resize inspector"/><Panel id="details" defaultSize="23%" minSize={narrow?0:"230px"} maxSize={narrow?"100%":"45%"} collapsible panelRef={right}><aside id="inspector" inert={narrow&&A.session.mobilePane!=='right'} aria-label="Selection inspector"/></Panel></Group>}
const frameRoot=createRoot(document.getElementById('workspace'));flushSync(()=>frameRoot.render(<Frame/>));
edit=function(){old.edit();changed()};sessionEdit=function(){old.sessionEdit();changed()};setEnvelope=function(env,session){old.setEnvelope(env,session);if(lastProject!==env.projectId){A.localCatalogue=[];A.catalogueGroups=[];A.lastCheck=null;A.selectedEvidence=null;lastProject=env.projectId;queueMicrotask(loadLocalCatalogue)}changed()};
function svg(Icon,size=17){return renderToStaticMarkup(<Icon size={size}/>)}
function tabButtons(items){return '<div class="subnav modern-tabs">'+items.map(([key,label])=>`<button data-tab="${key}" class="${A.session.tab===key?'active':''}">${label}</button>`).join('')+'</div>'}
// This app is the architecture/modeling/validation slice only -- Develop and Deploy are a
// separate, confidential tool, so the lifecycle bar has just the one stage now. Checking the
// model still works (the colored icon in the Architecture toolbar); it just isn't a separate
// top-level stage to navigate to, since checkModel() switches A.session.view itself.
nav=function(){const icons=[Compass],stages=['Architecture'];document.getElementById('lifecycle').innerHTML=stages.map((x,i)=>(i?'<span class="arrow" aria-hidden="true">'+svg(ChevronRight,12)+'</span>':'')+`<button data-view="${x}" class="${A.session.view===x?'active':''}" aria-label="${x}" title="${x}" ${A.session.view===x?'aria-current="page"':''}><span class="circle">${svg(icons[i],16)}</span><span class="step-label">${x}</span></button>`).join('');document.getElementById('lifecycle').classList.toggle('compact',A.session.compact);document.getElementById('compact-navigation').innerHTML=svg(A.session.compact?ChevronRight:ChevronLeft,15);document.getElementById('compact-navigation').title=A.session.compact?'Expand lifecycle':'Compact lifecycle';document.getElementById('project-name').textContent=name()};
context=function(){if(!A.env)return;const p=innerWidth<=900?{...panelState(),left:A.session.mobilePane!=='left',right:A.session.mobilePane!=='right'}:panelState();document.getElementById('contextbar').innerHTML=`<div class="context-tabs">${A.session.view==='Architecture'?tabButtons([['brief','Project brief'],['system','Architecture'],['repositories','Repositories'],['types','Data types']]):A.session.view==='Validate'?tabButtons([['checks','Checks']]):`<span>${esc(A.session.view)} workspace</span>`}</div><div class="context-actions"><button class="icon-button" data-action="tools" title="Tools for this stage" aria-label="Tools for this stage">${svg(Settings2)}</button><button class="icon-button" data-action="toggle-left" title="${p.left?'Show':'Hide'} explorer" aria-label="${p.left?'Show':'Hide'} explorer">${svg(p.left?PanelLeftOpen:PanelLeftClose)}</button><button class="icon-button" data-action="toggle-right" title="${p.right?'Show':'Hide'} inspector" aria-label="${p.right?'Show':'Hide'} inspector">${svg(p.right?PanelRightOpen:PanelRightClose)}</button></div>`;requestAnimationFrame(()=>document.querySelector('.modern-tabs button.active')?.scrollIntoView({block:'nearest',inline:'nearest'}));document.getElementById('root-path').textContent=A.env.root;document.getElementById('root-path').title=A.env.root;document.getElementById('sync-status').textContent=`${A.env.modelState||'draft'} · revision ${A.env.revision}`;if(innerWidth<=900){panelRefs.group?.current?.setLayout(mobileLayout());return}if(p.left)panelRefs.left?.current?.collapse();else if(panelRefs.left?.current?.isCollapsed())panelRefs.left.current.expand();if(p.right)panelRefs.right?.current?.collapse();else if(panelRefs.right?.current?.isCollapsed())panelRefs.right.current.expand()};
function simpleInspector(title,text){mount('inspector',<div className="inspector-document"><h2>{title}</h2><p>{text}</p><button onClick={()=>{A.agentOpen=true;renderAgent()}}><Sparkles size={15}/> Ask coding assistant</button></div>)}
function legacy(fn){release('main','explorer','inspector');legacyMode=true;fn();humanizeLegacyDOM(document.getElementById('main'));humanizeLegacyDOM(document.getElementById('inspector'));requestAnimationFrame(drawEdges)}
render=function(){if(!A.project){release('main','explorer','inspector');old.landing();return}document.getElementById('landing').classList.add('hidden');document.getElementById('workbench').classList.remove('hidden');
// Only Architecture and Validate render. Anything else -- a session saved before Develop/Deploy
// were removed, or a leftover go('Develop') somewhere -- used to leave the workbench showing
// whichever panels were mounted last, with a contextbar reading "Develop workspace" and no way
// back except guessing. Clamp instead of rendering a view that does not exist.
// (No sessionEdit() here -- this runs inside render, and sessionEdit is wrapped to call
// changed(); the clamp re-applies on every render anyway, so persisting it is not needed.)
if(!['Architecture','Validate'].includes(A.session.view)){A.session.view='Architecture';A.session.tab='system'}
nav();renderShortcuts();context();legacyMode=false;const view=A.session.view;if(view==='Architecture'){if(A.session.tab==='brief'){mount('main',<Intent/>);mount('explorer',<div className="inspector-document"><h2>Project definition</h2><a href="#" onClick={e=>{e.preventDefault();A.session.mobilePane=null;context();changed();requestAnimationFrame(()=>document.querySelector('.brief-fields')?.scrollIntoView({block:'start'}))}}>Purpose & constraints</a><a href="#" onClick={e=>{e.preventDefault();A.session.mobilePane=null;context();changed();requestAnimationFrame(()=>document.querySelector('.behavior-document')?.scrollIntoView({block:'start'}))}}>Behavior & recovery</a><a href="#" onClick={e=>{e.preventDefault();A.session.mobilePane=null;context();changed();requestAnimationFrame(()=>document.querySelector('.criteria-document')?.scrollIntoView({block:'start'}))}}>Acceptance checks</a><p className="panel-footnote">All edits save automatically. Components are created in Architecture, then assigned here.</p></div>);mount('inspector',<IntentGuide/>)}else if(A.session.tab==='types'){mount('main',<TypesWorkspace/>);mount('explorer',<Catalogue/>);simpleInspector('Data contracts','Messages have data fields. Services have a request and response. Actions have a goal, result and feedback. Type definitions are persisted for model generation and coding agents.')}else if(A.session.tab==='repositories'){mount('main',<RepositoryWorkspace/>);mount('explorer',<Catalogue/>);simpleInspector('Source → model → system','Extracted contracts become reusable catalogue entries. Review unresolved source expressions before publishing. Adding an instance to the system preserves its types and source provenance.')}else{A.session.tab='system';mount('main',<ArchitectureGraph/>);mount('explorer',<Catalogue/>);mount('inspector',<ComponentInspector/>)}}else if(view==='Validate'){A.session.tab='checks';mount('main',<div className="viewer-page"><ChecksView/></div>);mount('explorer',<ChecksExplorer/>);simpleInspector('Validation evidence','Check results identify what was inspected and what still needs work. Select a finding to return to the affected component.')}renderAgent();renderTutorial();changed();const savedLayout=A.session.splitLayouts?.[A.session.view];if(savedLayout&&innerWidth>900)requestAnimationFrame(()=>panelRefs.group?.current?.setLayout(savedLayout))};
validateView=function(){render()};systemView=function(){A.session.view='Architecture';A.session.tab='system';render()};brief=function(){A.session.view='Architecture';A.session.tab='brief';render()};nodeInspector=function(){if(A.session.view==='Architecture')mount('inspector',<ComponentInspector/>)};repositoriesPanel=async function(){A.session.view='Architecture';A.session.tab='repositories';sessionEdit();render()};
checkModel=async function(){if(!await flush())return;A.checkBusy=true;A.checkError='';A.session.view='Validate';A.session.tab='checks';sessionEdit();render();try{const pid=A.env.projectId,r=await api(`/projects/${pid}/validate`,{method:'POST',body:{expectedRevision:A.env.revision,kind:'model'}});if(A.env?.projectId!==pid)return;A.lastCheck=r;A.session.lastCheckEvidence=r.evidenceId||r.evidence?.id;sessionEdit();await refreshEvidence();await poll()}catch(e){A.checkError=e.message;banner(e.message)}finally{A.checkBusy=false;changed();saveState(A.dirty?'Saving…':'Saved to disk','saved')}};
modal=function(title,html){old.modal(title,html);humanizeLegacyDOM(document.getElementById('dialog-body'))};
showJob=function(job){A.lastJob=job;A.session.view='Validate';A.session.tab='checks';render();changed()};
pollJob=async function(){if(!A.jobId||!A.env)return;const pid=A.env.projectId,id=A.jobId;try{const job=await api(`/projects/${pid}/jobs/${id}`);if(A.env?.projectId!==pid||A.jobId!==id)return;A.lastJob=job;changed();if(['queued','running','starting','cancelling'].includes(job.status||job.state))setTimeout(pollJob,900);else refreshArtifacts()}catch(e){banner(e.message)}};
function Assistant(){useStudio();const[busy,setBusy]=useState(false),[result,setResult]=useState('');return <div className="assistant-panel"><div className="panel-heading"><h2><Sparkles size={17}/> Coding assistant</h2><IconButton icon={X} label="Close assistant" onClick={()=>{A.agentOpen=false;if(innerWidth<=900)A.session.mobilePane=null;render()}}/></div><p>Uses your installed CLI in this project. File changes return to Studio automatically.</p><Field label="Coding tool"><select aria-label="Coding tool" value={A.session.provider||'codex'} onChange={e=>{A.session.provider=e.target.value;A.handoff=null;sessionEdit()}}><option value="codex">Codex CLI</option><option value="claude">Claude Code</option><option value="gemini">Gemini CLI</option><option value="antigravity">Antigravity CLI</option></select></Field><Field label="What should the agent do?"><textarea aria-label="Coding task" rows={10} value={A.session.agentTask||''} placeholder="Implement the task interpreter and its clarification recovery paths…" onChange={e=>{A.session.agentTask=e.target.value;A.handoff=null;sessionEdit()}}/></Field><div className="assistant-scope"><FolderGit2 size={16}/><span>Working directory<small>{agentDirectory()}</small></span></div><button className="primary" disabled={busy||!A.session.agentTask?.trim()} onClick={async()=>{if(!await flush())return;setBusy(true);setResult('Preparing your task and project context…');try{const pid=A.env.projectId;const r=await api(`/projects/${pid}/handoff`,{method:'POST',body:{provider:A.session.provider||'codex',task:A.session.agentTask,selectedIds:A.session.selectedNode?[A.session.selectedNode]:[]}});A.handoff=r;await api(`/projects/${pid}/tools/open`,{method:'POST',body:{kind:'agent',handoffId:r.handoffId}});tutorialProof('handoffOrEditor');setResult('Terminal opened with your complete task. Studio will show files changed by the agent.')}catch(e){setResult(e.message)}finally{setBusy(false)}}}><Play size={15}/>{busy?'Opening…':'Open CLI with this task'}</button>{result&&<p className="inline-note" role="status">{result}</p>}<details><summary>Context included with the task</summary><p>The full project file path, brief and failure branches, selected component interfaces (or all components when none is selected), and the repository’s ROS model skill.</p></details></div>}
renderAgent=function(){document.getElementById('agent-drawer').classList.add('hidden');document.getElementById('agent-launcher').classList.add('hidden');if(A.env&&A.agentOpen){const p=panelState();p.right=false;panelRefs.right?.current?.expand();mount('inspector',<Assistant/>)}};
renderShortcuts=function(){old.renderShortcuts();const map={'coding-cli':Sparkles,mujoco:Box,evidence:GitCompare,'node-skeletons':FileCode,'model-check':ShieldCheck,compose:Container,repositories:FolderGit2};for(const el of document.querySelectorAll('[data-run-tool]')){const icon=map[el.dataset.runTool];if(icon){el.innerHTML=svg(icon);el.classList.add('icon-button')}}};
const originalNodeCard=nodeCard;nodeCard=function(n,position){let html=originalNodeCard(n,position);const responsibility={Unassigned:'Not assigned',Afferent:'Sense & interpret',Core:'Decide & plan',Efferent:'Act & communicate',Meta:'Monitor & recover',Supporting:'Support'}[moduleMeta(n).role];if(responsibility)html=html.replace('<small>'+esc(moduleMeta(n).role)+'</small>','<small>'+esc(responsibility)+'</small>');return html};
const originalAction=action;action=async function(key){if(innerWidth<=900&&['toggle-left','toggle-right'].includes(key)){const pane=key==='toggle-left'?'left':'right';A.session.mobilePane=A.session.mobilePane===pane?null:pane;changed();context();return}if(key==='layout'){banner('Drag the separators between panels to resize. Double-click a separator to reset its layout.');return}if(key==='agent'){A.agentOpen=!A.agentOpen;if(A.agentOpen){if(innerWidth<=900)A.session.mobilePane='right';renderAgent();context();changed()}else{if(innerWidth<=900)A.session.mobilePane=null;render()}return}return originalAction(key)};
document.addEventListener('dblclick',e=>{if(e.target.closest('.panel-separator')){A.session.splitLayouts=A.session.splitLayouts||{};delete A.session.splitLayouts[A.session.view];panelRefs.group?.current?.setLayout({catalogue:21,work:56,details:23});sessionEdit()}});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'&&!e.target.closest('input,textarea,[contenteditable]')&&A.session.view==='Architecture'){e.preventDefault();if(e.shiftKey)redo();else undo()}});
window.addEventListener('resize',()=>{if(A.env){changed();context()}});
window.StudioEditor={connectInterfaces,connectionProblem,instantiate,changed,loadLocalCatalogue,panels:panelRefs};
document.body.classList.add('modern-studio');document.querySelector('.brand').innerHTML=svg(Box,21)+'<span>CoreSense <b>Studio</b></span>';document.querySelector('header [data-action="settings"]').innerHTML=svg(Settings2);document.querySelector('header [data-action="tutorials"]').innerHTML=svg(BookOpen)+'<span>Learn</span>';
if(A.project){lastProject=A.env.projectId;loadLocalCatalogue();render()}else old.landing();
