import React,{useEffect,useState,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {FileText,FileCode,FolderOpen,Code,Play,CheckCircle2,AlertTriangle,Clock,ArrowRight,Download,Search,RefreshCw,Boxes,ExternalLink,Eye,GitCompare,Check,ChevronRight} from 'lucide-react';
import {useStudio,changed,go,Field,IconButton,kinds,valueText} from './state.jsx';

const labels={byNode:'Findings by module',global:'Project findings',nodeId:'Module',moduleId:'Module',nodeIds:'Modules',projectId:'Project identifier',modelState:'Model file status',modelHashes:'Model file identities',sourceHashes:'Source file identities',inputHashes:'Input file identities',candidateHash:'Candidate identity',snapshotHash:'Captured input identity',sourcePaths:'Relevant files',generatedPaths:'Generated files',capturedAt:'Captured',createdAt:'Created',receivedAt:'Last received',ageSeconds:'Sample age (seconds)',rateHz:'Rate (Hz)',exitCode:'Exit code',rosDistro:'ROS distribution',domainId:'ROS domain',launchArgv:'Launch command',node_namespace:'Namespace',portBindings:'Runtime names',checkIds:'Check records',missingInputs:'Not captured or checked',implementationStatus:'Implementation',fileHashes:'File identities',reviewer:'Reviewed by',qos:'Quality of service',lease_duration:'Liveliness lease',failures:'Failure conditions',recoveries:'Recovery actions',kind:'Record type'};
const label=k=>labels[k]||String(k).replace(/([a-z])([A-Z])/g,'$1 $2').replace(/[_-]/g,' ').replace(/^./,c=>c.toUpperCase());
const empty=v=>v===null||v===undefined||v==='';
const summary=v=>v&&typeof v==='object'?(v.label||v.name||v.action||v.message||v.path||v.topic||v.id):valueText(v);
const stringify=v=>JSON.stringify(v,null,2);
const nodeName=id=>A.project?.nodes?.find(n=>n.id===id)?.label||id;
function focusNode(id){A.session.selectedNode=id;sessionEdit();go('Architecture','system');changed()}
async function perform(fn){try{await fn();changed()}catch(e){banner(e.message||String(e))}}
function downloadJSON(name,value){const url=URL.createObjectURL(new Blob([stringify(value)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export function Status({value}){const v=String(value||'not-run').toLowerCase(),good=['passed','accepted','clean','current','complete','succeeded'].includes(v),bad=['failed','rejected','error','conflict','external-invalid','changes-requested'].includes(v);const Icon=good?CheckCircle2:bad?AlertTriangle:Clock;return <span className={'tag '+(good?'ok':bad?'warn':'')} style={{display:'inline-flex',alignItems:'center',gap:5}}><Icon size={14}/>{label(v)}</span>}
function Empty({title,children}){return <div className="hint"><strong>{title}</strong>{children&&<p>{children}</p>}</div>}
function Raw({value,text,filename='record.json'}){return <details className="section"><summary>Raw file & export</summary><div className="toolbar"><button onClick={()=>text!==undefined?downloadText(filename,text):downloadJSON(filename,value)}><Download size={15}/> Download {filename}</button></div><pre data-humanized="raw" style={{maxHeight:440,overflow:'auto',whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{text!==undefined?text:stringify(value)}</pre></details>}
function downloadText(filename,text){const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}

/** Structured data as labelled facts. Raw JSON is never the default view. */
export function HumanData({value,depth=0,name}){
 if(empty(value))return <span className="muted">Not specified</span>;
 if(depth>6)return <details><summary>More detail</summary><span>{Array.isArray(value)?`${value.length} entries`:'Additional structured fields'}</span><Raw value={value}/></details>;
 if(typeof value==='string'&&/^data:image\/(png|jpeg|webp);base64,/.test(value))return <img src={value} alt="Captured image" style={{maxWidth:'100%',maxHeight:400}}/>;
 if(typeof value==='string'&&value.length>1200)return <details><summary>Long text ({value.length.toLocaleString()} characters)</summary><span style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{value}</span></details>;
 if(typeof value!=='object')return <span style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{typeof value==='boolean'?(value?'Yes':'No'):String(value)}</span>;
 if(Array.isArray(value)){
  if(!value.length)return <span className="muted">None recorded</span>;
  if(value.every(v=>v===null||typeof v!=='object'))return <ul>{value.slice(0,100).map((v,i)=><li key={i}><HumanData value={v} depth={depth+1}/></li>)}{value.length>100&&<li>{value.length-100} more entries in the export</li>}</ul>;
  return <div>{value.slice(0,60).map((v,i)=><details key={i} open={value.length<5} className="section"><summary>{String(summary(v)||`${name||'Entry'} ${i+1}`).slice(0,160)}</summary><HumanData value={v} depth={depth+1}/></details>)}{value.length>60&&<p>{value.length-60} additional entries in the export.</p>}</div>;
 }
 const entries=Object.entries(value);if(!entries.length)return <span className="muted">No fields recorded</span>;
 return <dl className="human-facts" style={{display:'grid',gridTemplateColumns:depth===0?'minmax(140px, 28%) minmax(0, 1fr)':'minmax(110px, 30%) minmax(0, 1fr)',gap:'10px 18px',margin:'12px 0'}}>{entries.map(([key,v])=><React.Fragment key={key}><dt style={{fontWeight:600,overflowWrap:'anywhere'}}>{label(key)}</dt><dd style={{margin:0,minWidth:0}}>{['nodeId','moduleId'].includes(key)&&typeof v==='string'&&A.project?.nodes?.some(n=>n.id===v)?<button onClick={()=>focusNode(v)}>{nodeName(v)} <ArrowRight size={13}/></button>:<HumanData value={v} depth={depth+1} name={label(key)}/>}</dd></React.Fragment>)}</dl>;
}
function ModuleList({selected,onSelect,search=''}){return <div>{(A.project?.nodes||[]).filter(n=>(n.label+' '+n.pkg).toLowerCase().includes(search.toLowerCase())).map(n=><button key={n.id} className={'list-button '+(selected===n.id?'active':'')} onClick={()=>onSelect(n.id)}><strong>{n.label}</strong><small>{n.pkg||'Package not set'}</small></button>)}</div>}
function pickNode(id){A.session.selectedNode=id;A.artifact=null;sessionEdit();changed()}
export function DevelopExplorer(){const a=useStudio(),[search,setSearch]=useState('');return <><h2>Modules</h2><Field label="Find a module"><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name or package"/></Field><button className={'list-button '+(!a.session.selectedNode?'active':'')} onClick={()=>pickNode(null)}>All project files</button><ModuleList selected={a.session.selectedNode} onSelect={pickNode} search={search}/><p className="mini muted">Select a module to see its contracts, source and startup files.</p></>}
const artifactGroup=f=>f.path==='project.json'||/\.(rossystem|ros2|ros)$/.test(f.path)?'Contracts':/launch|config|\.ya?ml$/.test(f.path)&&!f.path.startsWith('deploy/')?'Startup & configuration':f.path.startsWith('deploy/')||f.path==='repositories.repos'?'Deployment & sources':/test|\.urdf$|\.xacro$|\.mjcf$/.test(f.path)?'Robot & tests':'Implementation';
const purpose=f=>f.path==='project.json'?'Editable project model, intent and module mappings.':f.path.endsWith('.rossystem')?'System composition and declared connections.':f.path.endsWith('.ros2')?'Package node interfaces and parameters.':f.path.endsWith('.ros')?'Message, service and action contracts.':f.path.endsWith('compose.yaml')?'Container allocation, source mounts and launch commands.':f.path.endsWith('package.xml')?'ROS package identity and dependencies.':f.path.endsWith('setup.py')?'Python package installation and executable entry points.':f.path.includes('launch')?'Which processes start and how they are configured.':f.path.startsWith('src/')?'Application source or resources.':'Project configuration or supporting artifact.';
function relevant(f,a){const id=a.session.selectedNode;if(!id)return true;const paths=a.project.studio?.modules?.[id]?.sourcePaths||[];return f.path==='project.json'||f.moduleIds?.includes(id)||paths.includes(f.path)||/\.(rossystem|ros2|ros)$/.test(f.path)&&(!f.moduleIds?.length||f.moduleIds.includes(id))}
async function openArtifact(f){const id=A.env.projectId;const data=await api(`/projects/${id}/file?path=${encodeURIComponent(f.path)}`);if(A.env?.projectId!==id)return;A.artifact={...f,...data};changed()}
function ProjectOverview({project}){if(!project?.system)return <HumanData value={project}/>;const studio=project.studio||{};return <><h2>{project.system.name}</h2><p>{studio.brief?.purpose||'Add the project purpose in Architecture.'}</p><div className="grid2"><section><h3>Constraints</h3><p>{studio.brief?.constraints||'Not defined'}</p></section><section><h3>Acceptance</h3><p>{studio.brief?.acceptance||'Not defined'}</p></section></div><h3>Modules</h3><ul>{project.nodes?.map(n=><li key={n.id}><strong>{n.label}</strong> · {n.pkg||'No package'} · {n.ifaces?.length||0} interfaces</li>)}</ul><h3>Behavior</h3>{studio.behavior?.length?<ol>{studio.behavior.map(s=><li key={s.id}><strong>{s.action||'Untitled action'}</strong>{s.moduleId&&<> · {nodeName(s.moduleId)}</>}{s.failures?.map(f=><p key={f.id}>If {f.condition||'failure condition not set'}: {f.recoveries?.map(r=>r.action).join(' → ')||'No recovery defined'}</p>)}{s.recovery&&<p>Recovery: {s.recovery}</p>}</li>)}</ol>:<p className="muted">No behavior steps recorded.</p>}</>}
function ComposeOverview({value}){const services=value?.services;if(!services)return <><h3>Configured units</h3><HumanData value={A.project.studio?.deployment?.units||[]}/><p className="muted">Open Source to inspect the exact Compose file.</p></>;return <>{Object.entries(services).map(([id,u])=><section className="panel section" key={id}><h3><Boxes size={18}/> {id}</h3><dl><dt>Image</dt><dd>{u.image||'Not set'}</dd><dt>Launch command</dt><dd><code>{Array.isArray(u.command)?u.command.join(' '):u.command||'Image default'}</code></dd><dt>Network</dt><dd>{u.network_mode||'Compose network'}</dd><dt>ROS domain</dt><dd>{u.environment?.ROS_DOMAIN_ID??'Not specified'}</dd></dl><h4>Mounted files</h4><ul>{(u.volumes||[]).map((v,i)=><li key={i}>{typeof v==='string'?v:<><code>{v.source}</code> → <code>{v.target}</code> ({v.read_only?'read only':'editable'})</>}</li>)}</ul></section>)}</>}
function ArtifactDetail({artifact}){const [tab,setTab]=useState('overview');useEffect(()=>setTab('overview'),[artifact?.path]);if(!artifact)return <Empty title="Choose a file">Open an artifact above to inspect its purpose and contents here.</Empty>;const text=artifact.text??artifact.content??'';let parsed;try{parsed=JSON.parse(text)}catch{};const json=artifact.path.endsWith('.json');return <section className="panel section" aria-label="Artifact details"><div className="row between"><div><h2>{artifact.path.split('/').at(-1)}</h2><code>{artifact.path}</code></div><button onClick={()=>perform(()=>action('editor'))}><ExternalLink size={15}/> Open in editor</button></div><p>{purpose(artifact)}</p><div className="toolbar"><button aria-pressed={tab==='overview'} onClick={()=>setTab('overview')}>Overview</button><button aria-pressed={tab==='source'} onClick={()=>setTab('source')}>Source</button><button onClick={()=>downloadText(artifact.path.split('/').at(-1),text)}><Download size={15}/> Download</button></div>{artifact.binary?<p>This is a binary artifact; open it in its native tool.</p>:tab==='source'?<pre data-humanized="source" style={{whiteSpace:'pre-wrap',maxHeight:620,overflow:'auto'}}>{text}</pre>:artifact.path==='project.json'?<ProjectOverview project={parsed}/>:artifact.path.endsWith('compose.yaml')?<ComposeOverview value={parsed}/>:json&&parsed?<HumanData value={parsed}/>:<><div className="grid2"><section><h3>Ownership</h3><p>{artifact.owner==='generated'?'Generated artifact. Review changes before writing.':'Project-owned file. Keep handwritten work in your editor.'}</p></section><section><h3>Check this file</h3><p>{artifact.path.includes('launch')?'Check launch configuration, process startup and clean shutdown in Docker.':/\.(ros|ros2|rossystem)$/.test(artifact.path)?'Run the model checks, then review the recorded findings.':artifact.path.startsWith('src/')?'Build and test the relevant ROS package in its Docker environment.':'Review its values and the tool that consumes them.'}</p></section></div><p>The exact contents are available in the Source tab.</p></>}</section>}
export function DevelopView(){const a=useStudio(),[search,setSearch]=useState('');const files=(a.artifacts||[]).filter(f=>relevant(f,a)&&(f.path+' '+f.kind).toLowerCase().includes(search.toLowerCase()));const node=a.project.nodes.find(n=>n.id===a.session.selectedNode);return <><header><h1>{node?`Develop ${node.label}`:'Develop the system'}</h1><p>Review generated contracts, implement behavior in your editor, then build and check the result.</p></header><div className="toolbar"><button onClick={()=>perform(()=>generation('models'))}><FileText size={16}/> Generate model files</button><button onClick={()=>perform(()=>generation('code'))}><Code size={16}/> Generate node skeletons</button><button onClick={()=>perform(()=>action('editor'))}><ExternalLink size={16}/> Open editor</button><button onClick={()=>perform(()=>action('agent'))}>Ask coding agent</button></div><Field label="Find a relevant file"><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name, path or kind"/></Field>{files.length?['Contracts','Startup & configuration','Implementation','Robot & tests','Deployment & sources'].map(group=>{const entries=files.filter(f=>artifactGroup(f)===group);return entries.length?<section key={group} className="section"><h2>{group}</h2>{entries.map(f=><button key={f.path} className={'list-button '+(a.artifact?.path===f.path?'active':'')} onClick={()=>perform(()=>openArtifact(f))} style={{display:'flex',justifyContent:'space-between',alignItems:'center',width:'100%',textAlign:'left'}}><span><strong>{f.path}</strong><small>{purpose(f)}</small></span><span className="tag">{f.exists===false?'Not generated':f.owner==='generated'?'Generated':'Project file'}</span></button>)}</section>:null}):<Empty title="No files match this view">Generate the model or node skeletons, select another module, or clear the search.</Empty>}<ArtifactDetail artifact={files.some(f=>f.path===a.artifact?.path)?a.artifact:null}/></>}

export function checkList(a){return a.lastCheck?.checks||a.lastCheck?.evidence?.checks||[]}
function Findings({items,nodeId}){
 if(items&&!Array.isArray(items)&&typeof items==='object'&&('global' in items||'byNode' in items))return <><Findings items={items.global}/>{Object.entries(items.byNode||{}).map(([id,findings])=><Findings key={id} items={findings} nodeId={id}/>)}</>;
 return <>{(Array.isArray(items)?items:items?[items]:[]).map((d,i)=>{const linked=typeof d==='object'&&d?d.nodeId||nodeId:nodeId;return <article className="panel section finding" key={i}>{linked&&<h3>{nodeName(linked)}</h3>}{typeof d==='string'?<p>{d}</p>:<><strong>{d.message||d.title||d.rule||'Finding'}</strong>{d.severity&&<Status value={d.severity}/>}<p>{d.file&&<code>{d.file}{d.line?`:${d.line}`:''}</code>}</p>{d.hint&&<p>{d.hint}</p>}{d.suggestion&&<p>{d.suggestion}</p>}{!d.message&&!d.title&&!d.rule&&<HumanData value={d}/>}</>}{linked&&<button onClick={()=>focusNode(linked)}>Open {nodeName(linked)} <ArrowRight size={13}/></button>}</article>})}</>;
}
export function ChecksExplorer(){const a=useStudio();return <><h2>Model checks</h2><p className="mini muted">Declared interfaces, connections and model files.</p>{checkList(a).map((c,i)=><button className="list-button" key={i} onClick={()=>document.getElementById(`check-${i}`)?.scrollIntoView({behavior:'smooth'})}><strong>{c.name||c.label||'Check'}</strong><Status value={c.status}/></button>)}<button onClick={()=>perform(()=>action('validate'))}>Run model checks</button></>}
export function ChecksView(){const a=useStudio(),checks=checkList(a),diagnostics=a.lastCheck?.diagnostics||{},[search,setSearch]=useState('');return <><header><h1>Check the design</h1><p>Resolve model findings before building and running the system. A passed design check does not prove runtime behavior.</p></header><div className="toolbar"><button className="primary" disabled={a.checkBusy} onClick={()=>perform(()=>action('validate'))}><Play size={16}/> Run model checks</button><button onClick={()=>go('Architecture','system')}>Back to architecture</button></div>{a.lastCheck?.evidenceId&&<p className="hint">These results were saved as an evidence record.</p>}{a.checkBusy&&<p role="status">Running model checks…</p>}{a.checkError&&<p role="alert">{a.checkError}</p>}<Field label="Find a check or finding"><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name, module or message"/></Field>{checks.length?checks.map((c,i)=>JSON.stringify(c).toLowerCase().includes(search.toLowerCase())?<section key={i} id={`check-${i}`} className="panel section"><div className="row between"><h2>{c.name||c.label||'Check'}</h2><Status value={c.status}/></div>{c.message&&<p>{c.message}</p>}{c.status==='not-run'&&<p>This check has not run. Its result is unknown.</p>}<Findings items={c.diagnostics||c.findings}/>{c.output&&<details><summary>Tool output</summary><pre data-humanized="source">{c.output}</pre></details>}{c.status==='passed'&&!c.diagnostics?.length&&<p>No findings were reported by this check.</p>}</section>:null):<Empty title="No check results yet">Run the model checks against this project's current files.</Empty>}<Findings items={diagnostics.global}/>{Object.entries(diagnostics.byNode||{}).map(([id,items])=><section key={id}><h2>{nodeName(id)}</h2><Findings items={items} nodeId={id}/></section>)}{a.lastJob&&<DockerJobResult job={a.lastJob}/>} {a.lastCheck&&<Raw value={a.lastCheck} filename="model-check-results.json"/>}</>}

function RecordedCamera({sample}){const canvas=useRef(null),[error,setError]=useState('');useEffect(()=>{try{if(sample.message?.dataBase64&&typeof paintImage==='function'){paintImage(canvas.current,sample.message,sample.type);setError('')}else setError('No decodable image was captured.')}catch(e){setError(e.message)}},[sample]);return <>{error?<p>{error}</p>:null}<canvas ref={canvas} aria-label={`Recorded camera ${sample.topic}`} style={{maxWidth:'100%',maxHeight:350,display:error?'none':'block'}}/></>}
function RecordedTrace({history,kind='plot'}){if(!history?.length)return <p className="muted">No trace samples were captured.</p>;let html='';try{if(typeof trace==='function')html=trace(history,kind,'both')}catch{}return html?<div dangerouslySetInnerHTML={{__html:html}}/>:<p>{history.length} trace samples are available in the downloaded record.</p>}
function SimulationSummary({capture,showTrace=true}){const image=capture.imagePng||capture.screenshot||capture.image||capture.png;return <>{image&&<img className="evidence-image" src={image} alt="Captured simulation viewport" style={{maxWidth:'100%',maxHeight:400}}/>}<p>MuJoCo {capture.engineVersion||'version not recorded'} · simulation time {Number(capture.time||0).toFixed(3)} s</p><h3>Inputs and outcomes</h3><HumanData value={{parameters:capture.parameters,time:capture.time,qpos:capture.qpos,sensors:capture.sensors,contacts:capture.contacts}}/>{showTrace&&<><h3>Recorded motion</h3><RecordedTrace history={(capture.trace||[]).map(s=>({time:s.time,message:{qpos:s.qpos,sensors:s.sensors}}))}/><p className="mini muted">{capture.trace?.length||0} captured samples{capture.traceDropped?`; ${capture.traceDropped} older samples omitted`:''}.</p></>}</>}
function RecordedSamples({samples=[]}){return <>{samples.map((s,i)=>{const kind=typeof widgetKind==='function'?widgetKind(s.type||''):'listener';return <section className="panel section" key={i}><h3>{s.topic||'Recorded topic'}</h3><p>{s.type} · {s.count??0} messages · {Number(s.rateHz||0).toFixed(1)} Hz</p>{s.message?.header?.frame_id&&<p>Frame: {s.message.header.frame_id}</p>}{kind==='camera'?<RecordedCamera sample={s}/>:['wrench','plot'].includes(kind)?<RecordedTrace history={s.history} kind={kind}/>:<HumanData value={s.message}/>}</section>})}</>}
async function rerunRecord(record){const checks=record.checks||[];if(checks.some(c=>c.job?.kind==='tutorial-test'))await startJob('test');else if(checks.some(c=>c.job?.kind==='tutorial-build'))await startJob('build');else await checkModel()}
export function EvidenceDetail({record}){const capture=record.observations?.capture;return <section className="panel section"><h2>{record.label||record.title||'Evidence record'}</h2><p>{record.capturedAt||record.createdAt} · revision {record.revision}</p><p className="mini muted">Read-only captured state. Opening this record does not replace the working model.</p>{capture&&<><SimulationSummary capture={capture}/><button onClick={()=>perform(async()=>{await changeView('Validate','simulation');if(typeof replayPhysicsEvidence!=='function')throw Error('The simulation viewer is not available.');await replayPhysicsEvidence(record)})}>Open recorded simulation</button></>}{record.observations?.samples?.length>0&&<><h3>Recorded ROS observations</h3><RecordedSamples samples={record.observations.samples}/></>}{record.snapshot?.engineering&&<details><summary>Captured project definition</summary><ProjectOverview project={record.snapshot.engineering}/></details>}<h3>Recorded checks</h3>{record.checks?.length?record.checks.map((c,i)=><section key={i} className="panel section"><strong>{c.name||c.evidenceId||'Check result'}</strong><Status value={c.status||c.job?.status||'linked result'}/><Findings items={c.diagnostics}/>{c.results&&<HumanData value={c.results}/>} {c.job&&<HumanData value={{kind:c.job.kind,status:c.job.status,exitCode:c.job.exitCode,coverage:c.job.coverage}}/>}</section>):<p>No check result is attached to this capture.</p>}{record.kind==='check'&&<button onClick={()=>perform(()=>rerunRecord(record))}>Rerun recorded check</button>}<h3>Limits</h3><HumanData value={record.missingInputs||[]}/><Raw value={record} filename="evidence-record.json"/></section>}
function EvidenceComparison({comparison}){const [first,second]=comparison.records,ca=first.observations?.capture,cb=second.observations?.capture;const filtered=(comparison.differences||[]).filter(d=>!/(imagePng|screenshot|dataBase64|\.(history|trace)\[|\.(qpos|qvel|sensors)\[|\.message\.(data|ranges|intensities)\[)/.test(d.path));const shown=filtered.slice(0,120);return <section className="panel section"><h2>Evidence comparison</h2><div className="grid2">{[first,second].map((r,i)=><section key={i}><h3>{r.label||`Record ${i+1}`}</h3><p>{r.capturedAt} · revision {r.revision}</p>{r.observations?.capture?<SimulationSummary capture={r.observations.capture}/>:r.observations?.samples?.length?<RecordedSamples samples={r.observations.samples}/>:<p>{label(r.kind||'design')} record</p>}</section>)}</div>{ca&&cb&&<p className="hint">{ca.sceneHash===cb.sceneHash&&ca.engineVersion===cb.engineVersion?'Same scene and engine. Review parameter changes before interpreting the outcomes.':'Different scene or engine. These results are not directly equivalent.'}</p>}<h3>Engineering and result changes</h3><p>{filtered.length} summary changes. Image bytes and individual trace samples remain in the full records.</p>{shown.length?shown.map((d,i)=><article key={i} className="section"><h4>{String(d.path||'Change').split('.').map(label).join(' / ')}</h4><div className="grid2"><section><strong>First record</strong><HumanData value={d.before}/></section><section><strong>Second record</strong><HumanData value={d.after}/></section></div></article>):<p>No changed engineering inputs or summary results.</p>}{filtered.length>shown.length&&<p>{filtered.length-shown.length} further changes are in the download.</p>}<h3>Comparison limits</h3><HumanData value={comparison.missingInputs||[]}/><button onClick={()=>downloadJSON('evidence-comparison.json',comparison)}>Download comparison and both full records</button><Raw value={comparison} filename="evidence-comparison.json"/></section>}
export function EvidenceViewReact(){const a=useStudio(),[search,setSearch]=useState(''),[opened,setOpened]=useState(null),[selected,setSelected]=useState([]),[comparison,setComparison]=useState(null);useEffect(()=>{setOpened(null);setSelected([]);setComparison(null)},[a.env?.projectId]);const records=(a.evidence||[]).filter(r=>`${r.label||r.title||''} ${r.kind||''}`.toLowerCase().includes(search.toLowerCase()));async function open(id){const pid=A.env.projectId,result=await api(`/projects/${pid}/evidence/${encodeURIComponent(id)}`);if(A.env.projectId===pid){setOpened(result.evidence||result);A.openRecord=result.evidence||result;setComparison(null)}}async function compare(){const pid=A.env.projectId,[one,two,result]=await Promise.all([api(`/projects/${pid}/evidence/${selected[0]}`),api(`/projects/${pid}/evidence/${selected[1]}`),api(`/projects/${pid}/evidence/compare?a=${selected[0]}&b=${selected[1]}`)]);if(A.env.projectId!==pid)return;const pair=[one.evidence,two.evidence];A.comparedEvidence=pair;if(typeof tutorialProof==='function'){if(pair.every(r=>r.kind==='simulation'))tutorialProof('physicsCompared');if(pair.every(r=>r.kind==='design')&&pair[0].snapshot?.engineering?.studio?.brief?.acceptance!==pair[1].snapshot?.engineering?.studio?.brief?.acceptance)tutorialProof('designsCompared')}setComparison({...result,records:pair});setOpened(null)}return <><header><h1>Evidence library</h1><p>Inspect captured inputs, completed checks and changes between records.</p></header><div className="toolbar"><button onClick={()=>perform(()=>action('capture'))}>Capture design snapshot</button><button data-engineering="review">Record review</button><button data-engineering="delivery">Delivery history</button><button disabled={selected.length!==2} onClick={()=>perform(compare)}>Compare {selected.length}/2 selected</button></div><Field label="Find evidence"><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Title or type"/></Field>{records.length?records.map(r=><article key={r.id} className="panel row between section"><label className="row"><input type="checkbox" aria-label={`Compare ${r.label||r.title||r.id}`} checked={selected.includes(r.id)} disabled={selected.length===2&&!selected.includes(r.id)} onChange={e=>setSelected(e.target.checked?[...selected,r.id]:selected.filter(id=>id!==r.id))}/><span><strong>{r.label||r.title||'Untitled record'}</strong><small>{label(r.kind||r.recordType||'evidence')} · {r.capturedAt||r.createdAt}</small>{r.stale&&<span className="tag warn">Inputs changed since capture</span>}</span></label><button onClick={()=>perform(()=>open(r.id))}>Open record</button></article>):<Empty title="No evidence matches">Run a check or capture a snapshot to create a record.</Empty>}{opened&&<EvidenceDetail record={opened}/>} {comparison&&<EvidenceComparison comparison={comparison}/>}</>}

function DockerJobResult({job}){const running=['queued','running','starting','cancelling'].includes(job.status||job.state),id=job.jobId||job.id||A.jobId;return <section className="panel section"><div className="row between"><h2>Docker {job.kind==='tutorial-build'?'build':job.kind==='tutorial-test'?'test':'job'}</h2><Status value={job.status||job.state}/></div><HumanData value={job.coverage||'Coverage was not recorded.'}/><p>Exit code: {job.exitCode??'pending'}</p><pre data-humanized="source" id="live-job-log" style={{maxHeight:420,overflow:'auto',whiteSpace:'pre-wrap'}}>{job.logTail||job.log||'Waiting for output…'}</pre>{running?<button disabled={job.status==='cancelling'} onClick={()=>perform(async()=>{await api(`/projects/${A.env.projectId}/jobs/${id}/cancel`,{method:'POST',body:{}});await pollJob()})}>Cancel job</button>:<button onClick={()=>perform(async()=>{if(!await flush())return;await api(`/projects/${A.env.projectId}/jobs/${id}/evidence`,{method:'POST',body:{expectedRevision:A.env.revision}});await changeView('Validate','evidence')})}>Save job result as evidence</button>}</section>}

export function humanizeLegacyDOM(root=document){let count=0;for(const pre of root.querySelectorAll('pre:not([data-humanized])')){if(pre.closest('[data-humanized]'))continue;const text=pre.textContent.trim();if(!/^[\[{]/.test(text))continue;let data;try{data=JSON.parse(text)}catch{continue}const host=document.createElement('div');host.className='human-data section';host.dataset.humanized='true';pre.replaceWith(host);createRoot(host).render(<><HumanData value={data}/><Raw value={data}/></>);count++}return count}
